name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Apt Dependencies
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y libeigen3-dev libpcl-dev build-essential cmake gcc-11 g++-11

      - name: Homebrew Dependencies
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew update
          brew install cmake eigen pcl qt5 gcc@11 tbb

      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11 -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        run: cmake --build ${{github.workspace}}/build
