name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Apt Dependencies
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          sudo apt-add-repository -y "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y cmake libeigen3-dev libpcl-dev libomp-dev libtbb-dev gcc-11 g++-11

      - name: Homebrew Dependencies
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew update
          brew install cmake eigen pcl qt5 gcc@11 tbb

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11 -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWITH_TESTS=true -Wno-dev

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Test
        run: cd ${{github.workspace}}/build && make test
